apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadmus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadmus
  template:
    metadata:
      labels:
        app: cadmus
    spec:
      containers:
      - name: cadmus
        image: realartisan/cadmus:b338778_main_20250129T203732 # {"$imagepolicy": "flux-system:cadmus"}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
