apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cadmus
  namespace: flux-system
spec:
  image: realartisan/cadmus
  interval: 1m
  secretRef:
    name: dockerhub-secret

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cadmus
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cadmus
  filterTags:
    pattern: '^[a-f0-9]{7}_main_(?P<timestamp>\d{8}T\d{6})$'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: cadmus
  namespace: flux-system
spec:
  interval: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: main
  update:
    path: ./kubernetes/deployment.yaml
    strategy: Setters