apiVersion: v1
kind: Service
metadata:
  name: cadmus
  namespace: default
spec:
  selector:
    app: cadmus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30661
  type: NodePort